name: lint

on: [push]

permissions:
  checks: write
  pull-requests: write
  # for comment
  contents: write

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ruff-action
        uses: astral-sh/ruff-action@v3.0.1
